# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...95"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        if_no_uploads: error
      backend:
        target: 80%
        paths:
          - "backend/"
        flags:
          - backend
      frontend:
        target: 70%
        paths:
          - "frontend/"
        flags:
          - frontend

    patch:
      default:
        target: 70%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

ignore:
  - "backend/tests/"
  - "frontend/tests/"
  - "frontend/src/setupTests.ts"
  - "**/*.d.ts"
  - "**/*.config.{js,ts}"
  - "**/index.{js,ts,tsx}"

flags:
  backend:
    paths:
      - backend/
    carryforward: true
  frontend:
    paths:
      - frontend/
    carryforward: true

component_management:
  default_rules:
    flag_regexes:
      - "backend"
      - "frontend"

# Bundle Analysis Configuration
bundle_analysis:
  range: "60...100"

  status:
    project:
      default:
        target: 95%
        threshold: 1%
