name: Security Audit

on:
  schedule:
    - cron: "0 2 * * 1" # Weekly on Monday at 2 AM
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dependency-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit semgrep

      - name: Python dependency audit (Safety)
        working-directory: ./backend
        run: safety check -r requirements.txt --json --output safety-report.json || true

      - name: Python security linting (Bandit)
        working-directory: ./backend
        run: bandit -r app/ -f json -o bandit-report.json || true

      - name: Static analysis (Semgrep)
        working-directory: ./backend
        run: semgrep --config=auto app/ --json --output=semgrep-report.json || true

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Node.js dependency audit
        working-directory: ./frontend
        run: npm audit --audit-level=moderate --json > npm-audit-report.json || true

      - name: Upload security reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            backend/safety-report.json
            backend/bandit-report.json
            backend/semgrep-report.json
            frontend/npm-audit-report.json

  codeql-analysis:
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    strategy:
      matrix:
        language: ["python", "javascript"]

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
